### ISSUE TITLE
Printed URL is plain HTTP

### ISSUE THREAD

**Issue by andreyv** [tremby/imgur.sh#4]
The URL printed by the script has `http` scheme instead of `https`. Typical output:

```
> imgur.sh 123.jpg 
http://i.imgur.com/123.jpg
Delete page: https://imgur.com/delete/123456
```

**Comment by tremby** [comment]
That's because that's the URL which comes back from the API call.

I *could* add an option to do a string replacement on the URL which comes back, but I don't intend to add any options to this script. It's meant to be as simple as possible.

I *could* make it always do that string replacement. Are there strong reasons to? HTTPS has a latency hit, but you're then not leaking the URL to networks as the request travels.

Or maybe you could cook up some alias to manipulate the output of the script as it stands.

**Comment by andreyv** [comment]
HTTPS prevents MITM and sniffing attacks. Its percepted overhead is disputed in various sources, see https://istlsfastyet.com/ for example.

At any rate, if returning unmodified Imgur answer is by design, then it's fair enough.

**Comment by tremby** [comment]
Yes, I think it should continue to return the unmodified result. Perhaps if the API returned both an HTTP and an HTTPS URL I might choose to return the HTTPS one instead. But without it being offered, I don't think it's right to invent it, even though we're pretty sure it's going to be valid.

I think for now if it's important to you you should maintain a fork of the script, or cook up an alias or wrapper script to modify the output for you automatically.

**Comment by x89** [comment]
Ah okay, it's your decision and I respect that you're honouring the return results from Imgur. The unfortunate thing is that it means I'm going to have to maintain my own package now instead of having this incorporated into the Arch User Repository, which is fine, but I'm in favour of security everywhere for everyone.

Admittedly MitM on Imgur images is probably not the most pressing concern but it would allow for example governments and ISPs to identify browsing patterns and gather metrics on what you're doing, what you like, etc. HTTPS is a means of preventing this.

I'll maintain my own fork and create my own package for it then.

Thanks.

**Comment by tremby** [comment]
Hmm, I do agree with you on all of that. I'll make another request to
imgur. They should really be returning the https or both.

**Comment by tremby** [comment]
I've looked over the code again. On remembering that I invent the URL for the delete page from the a hash given by the API, I've changed my mind.

**Comment by tremby** [comment]
HTTPS URLs are now returned as of v7.

**Comment by tremby** [comment]
At some point in the ensuing years, the API has changed to now give back an HTTPS URL, so I've now removed the little filter which upgraded http to https.
